"""Build the named-region fixture and the migration 0016 rows from IHO Sea Areas v3 (ADR-0060).

Owner-run, with network access to the Marine Regions gazetteer and Docker for a disposable
PostGIS container that validates, clips and simplifies the polygons. Tests never run this; they
read the committed fixture and the generated block in the migration file.
"""

import argparse
import hashlib
import json
import re
import subprocess
import time
import urllib.request
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "packages/core/src/floatchat_core/query/regions/named_regions.json"
MIGRATION = ROOT / "infra/migrations/versions/0016_query_access.sql"
BEGIN = "-- BEGIN named_region rows (generated by scripts/build_named_regions.py; do not edit)"
END = "-- END named_region rows"
ENVELOPE = "POLYGON((20 -60,120 -60,120 30,20 30,20 -60))"
SOUTHERN = "POLYGON((20 -60,120 -60,120 -30,20 -30,20 -60))"
GAZETTEER = "https://www.marineregions.org/rest/getGazetteerGeometries.jsonld/{mrgid}/"
CITATION = (
    "Flanders Marine Institute (2018). IHO Sea Areas, version 3. Available online at "
    "https://www.marineregions.org/. https://doi.org/10.14284/323 (CC-BY 4.0)"
)
IHO_VERSION_PREFIX = "iho-v3-simplified-"
REGIONS = [
    {"name": "Arabian Sea", "kind": "iho", "mrgid": 4268},
    {"name": "Bay of Bengal", "kind": "iho", "mrgid": 4273},
    {"name": "Laccadive Sea", "kind": "iho", "mrgid": 4269},
    {"name": "Andaman Sea", "kind": "iho", "mrgid": 4274, "gazetteer_name": "Andaman or Burma Sea"},
    {"name": "Indian Ocean (IHO)", "kind": "iho", "mrgid": 1904, "gazetteer_name": "Indian Ocean"},
    {
        "name": "Indian Ocean",
        "kind": "operational",
        "version": "indian-ocean-v1",
        "wkt": ENVELOPE,
        "note": "The Stage 1 ingestion envelope (contract section 3.1); coverage is exactly the "
        "ingested domain.",
    },
    {
        "name": "Southern Indian Ocean",
        "kind": "operational",
        "version": "southern-indian-ocean-floatchat-v1",
        "wkt": SOUTHERN,
        "note": "The envelope south of 30S; a FloatChat definition, not an IHO area.",
    },
]


def fetch_wkts(mrgid: int) -> list[str]:
    with urllib.request.urlopen(GAZETTEER.format(mrgid=mrgid), timeout=120) as response:
        document = json.load(response)
    geometries = document.get("mr:hasGeometry") or []
    if isinstance(geometries, dict):
        geometries = [geometries]
    wkts = []
    for geometry in geometries:
        literal = geometry.get("gsp:asWKT")
        if isinstance(literal, dict):
            literal = literal.get("@value")
        if not isinstance(literal, str):
            continue
        literal = re.sub(r"^<[^>]+>\s*", "", literal.strip())
        if not re.match(r"^(MULTI)?POLYGON", literal):
            raise RuntimeError(f"unexpected geometry literal for MRGID {mrgid}")
        wkts.append(literal)
    if not wkts:
        raise RuntimeError(f"no polygon for MRGID {mrgid}")
    return wkts


class Postgis:
    def __init__(self, image: str) -> None:
        self.name = "floatchat-regions-" + uuid.uuid4().hex
        subprocess.run(
            [
                "docker",
                "run",
                "--detach",
                "--pull=never",
                "--network=none",
                "--memory=1g",
                "--name",
                self.name,
                "--env",
                "POSTGRES_HOST_AUTH_METHOD=trust",
                image,
            ],
            check=True,
            capture_output=True,
            timeout=60,
        )
        deadline = time.monotonic() + 60
        while True:
            ready = subprocess.run(
                ["docker", "exec", self.name, "pg_isready", "-h", "127.0.0.1", "-U", "postgres"],
                capture_output=True,
                timeout=10,
            )
            if ready.returncode == 0:
                break
            if time.monotonic() > deadline:
                raise RuntimeError("PostGIS container did not become ready")
            time.sleep(0.5)
        self.sql("CREATE EXTENSION IF NOT EXISTS postgis;")

    def sql(self, statement: str) -> str:
        result = subprocess.run(
            [
                "docker",
                "exec",
                "-i",
                self.name,
                "psql",
                "-X",
                "-q",
                "-t",
                "-A",
                "-U",
                "postgres",
                "-d",
                "postgres",
                "-v",
                "ON_ERROR_STOP=1",
            ],
            input=statement,
            text=True,
            capture_output=True,
            timeout=600,
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr[-2000:])
        return result.stdout.strip()

    def close(self) -> None:
        subprocess.run(
            ["docker", "rm", "--force", "--volumes", self.name], capture_output=True, timeout=60
        )


def dollar(text: str) -> str:
    tag = "$wkt$"
    assert tag not in text
    return tag + text + tag


def process(pg: Postgis, wkts: list[str], tolerance: float, min_area_km2: float) -> dict:
    """Union, make valid, clip to the envelope when needed, simplify; return facts."""
    union = " UNION ALL ".join(f"SELECT ST_GeomFromText({dollar(w)},4326) AS g" for w in wkts)
    pg.sql(
        f"DROP TABLE IF EXISTS src; CREATE TABLE src AS SELECT ST_MakeValid(ST_Union(g)) AS g "
        f"FROM ({union}) u;"
    )
    inside = (
        pg.sql(f"SELECT ST_Covers(ST_GeomFromText({dollar(ENVELOPE)},4326), g) FROM src") == "t"
    )
    clip = "" if inside else f"ST_Intersection(g, ST_GeomFromText({dollar(ENVELOPE)},4326))"
    expression = clip or "g"
    # Simplification can leave touching or overlapping rings; make valid, dissolve them
    # into one multipolygon and keep the polygonal part only.
    pg.sql(
        "DROP TABLE IF EXISTS simplified; CREATE TABLE simplified AS SELECT ST_Multi("
        f"ST_CollectionExtract(ST_UnaryUnion(ST_MakeValid(ST_SimplifyPreserveTopology({expression},"
        f" {tolerance}))), 3)) AS g FROM src;"
    )
    # Islands are holes and lagoons are small parts; neither can hold an ocean profile, so parts
    # and holes under the minimum area are dropped (recorded in the fixture).
    square_metres = min_area_km2 * 1e6
    pg.sql(
        "DROP TABLE IF EXISTS out; CREATE TABLE out AS SELECT ST_Multi(ST_UnaryUnion(ST_MakeValid("
        "ST_Collect(ST_MakePolygon(ST_ExteriorRing(d.geom), ARRAY(SELECT ST_ExteriorRing(r.geom) "
        "FROM ST_DumpRings(d.geom) r WHERE r.path[1] > 0 AND ST_Area(r.geom::geography) >= "
        f"{square_metres})))))) AS g FROM ST_Dump((SELECT g FROM simplified)) d "
        f"WHERE ST_Area(d.geom::geography) >= {square_metres};"
    )
    row = pg.sql(
        "SELECT ST_AsText(g) || E'\\n' || ST_IsValidReason(g) || E'\\n' || ST_NPoints(g) || E'\\n' || "
        "ST_XMin(g) || ',' || ST_YMin(g) || ',' || ST_XMax(g) || ',' || ST_YMax(g) || E'\\n' || "
        "(SELECT ST_NPoints(g) FROM src) || E'\\n' || ST_Area(g::geography)/1e6 FROM out"
    ).split("\n")
    wkt, valid, points, bbox, source_points, area = row
    assert valid == "Valid Geometry", f"simplified geometry invalid: {valid}"
    west, south, east, north = (float(v) for v in bbox.split(","))
    return {
        "wkt": wkt,
        "clipped": not inside,
        "vertices": int(points),
        "source_vertices": int(source_points),
        "area_km2": round(float(area), 1),
        "bbox": {"west": west, "south": south, "east": east, "north": north},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tolerance", type=float, default=0.05)
    parser.add_argument("--min-area-km2", type=float, default=50.0)
    parser.add_argument("--image", default="floatchat-stage0-wsl-dev-db:latest")
    args = parser.parse_args()
    pg = Postgis(args.image)
    try:
        rows = []
        for region in REGIONS:
            if region["kind"] == "iho":
                facts = process(pg, fetch_wkts(region["mrgid"]), args.tolerance, args.min_area_km2)
                version = f"{IHO_VERSION_PREFIX}{args.tolerance:g}-min{args.min_area_km2:g}km2-v1"
                source, source_id, tolerance = (
                    "marineregions-iho-v3",
                    f"MRGID {region['mrgid']}",
                    args.tolerance,
                )
                citation = CITATION
                note = f"Gazetteer name: {region.get('gazetteer_name', region['name'])}."
            else:
                facts = process(pg, [region["wkt"]], 0, 0)
                facts["wkt"] = pg.sql(
                    f"SELECT ST_AsText(ST_Multi(ST_GeomFromText({dollar(region['wkt'])},4326)))"
                )
                facts["clipped"] = False
                version, source, source_id, tolerance = region["version"], "floatchat", None, None
                citation = "FloatChat operational definition (docs/stage1-contract.md section 3.1, ADR-0060)"
                note = region["note"]
            rows.append(
                {
                    "name": region["name"],
                    "version": version,
                    "kind": region["kind"],
                    "source": source,
                    "source_id": source_id,
                    "citation": citation,
                    "simplify_tolerance_deg": tolerance,
                    "clipped": facts["clipped"],
                    "min_part_area_km2": args.min_area_km2 if region["kind"] == "iho" else None,
                    "bbox": facts["bbox"],
                    "vertices": facts["vertices"],
                    "source_vertices": facts["source_vertices"],
                    "area_km2": facts["area_km2"],
                    "note": note,
                    "wkt": facts["wkt"],
                    "sha256": hashlib.sha256(facts["wkt"].encode()).hexdigest(),
                }
            )
            print(
                f"{region['name']}: {facts['source_vertices']} -> {facts['vertices']} vertices, "
                f"clipped={facts['clipped']}, {len(facts['wkt'])} bytes WKT",
                flush=True,
            )
    finally:
        pg.close()
    FIXTURE.write_text(
        json.dumps(
            {"schema": "named-regions-fixture-v1", "regions": rows}, indent=1, sort_keys=True
        )
        + "\n"
    )
    lines = [BEGIN]
    for row in rows:
        values = ", ".join(
            [
                f"'{row['name']}'",
                f"'{row['version']}'",
                f"'{row['kind']}'",
                f"'{row['source']}'",
                "NULL" if row["source_id"] is None else f"'{row['source_id']}'",
                dollar(row["citation"]).replace("$wkt$", "$txt$"),
                "NULL"
                if row["simplify_tolerance_deg"] is None
                else str(row["simplify_tolerance_deg"]),
                "true" if row["clipped"] else "false",
                dollar(row["wkt"]),
                f"'{row['sha256']}'",
                str(row["bbox"]["west"]),
                str(row["bbox"]["south"]),
                str(row["bbox"]["east"]),
                str(row["bbox"]["north"]),
            ]
        )
        lines.append(
            "INSERT INTO app.named_region(name,version,kind,source,source_id,citation,"
            "simplify_tolerance_deg,clipped,wkt,sha256,bbox_west,bbox_south,bbox_east,bbox_north)\n"
            f"VALUES ({values})\nON CONFLICT (name,version) DO NOTHING;"
        )
    lines.append(END)
    text = MIGRATION.read_text()
    start, stop = text.index(BEGIN), text.index(END) + len(END)
    MIGRATION.write_text(text[:start] + "\n".join(lines) + text[stop:])
    print(f"wrote {FIXTURE.relative_to(ROOT)} and the rows block of {MIGRATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
