/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/catalog/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Coverage */
        get: operations["catalog_coverage_v1_catalog_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Parameters */
        get: operations["catalog_parameters_v1_catalog_parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/floats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Floats */
        get: operations["floats_v1_floats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/floats/{platform_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Float Detail */
        get: operations["float_detail_v1_floats__platform_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles */
        get: operations["profiles_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_v1_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Box */
        Box: {
            /** East */
            east: number;
            /** North */
            north: number;
            /** South */
            south: number;
            /** West */
            west: number;
        } & {
            [key: string]: unknown;
        };
        /** ChartAxes */
        ChartAxes: {
            x: components["schemas"]["ChartAxis"];
            y?: components["schemas"]["ChartAxis"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChartAxis */
        ChartAxis: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            /**
             * Reversed
             * @default false
             */
            reversed: boolean;
            /** Unit */
            unit?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChartData */
        ChartData: {
            /** Inline */
            inline: boolean;
            /** Points */
            points: number;
            /** Url */
            url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChartEncodings */
        ChartEncodings: {
            series: components["schemas"]["ChartAxis"];
            x: components["schemas"]["ChartAxis"];
            y?: components["schemas"]["ChartAxis"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChartSpec
         * @description The PRD 11.3 contract; ``plotly`` stays loose (allow-listed trace keys, see chart.py).
         */
        ChartSpec: {
            /** Aggregation */
            aggregation: string;
            axis: components["schemas"]["ChartAxes"];
            data: components["schemas"]["ChartData"];
            encodings: components["schemas"]["ChartEncodings"];
            /** Missing Value Policy */
            missing_value_policy: string;
            /** Plotly */
            plotly: {
                [key: string]: unknown;
            };
            /** Provenance Ref */
            provenance_ref: string;
            /** Series */
            series: string[];
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** CollectionResponse */
        CollectionResponse: {
            environment: components["schemas"]["Environment"];
            geography?: components["schemas"]["GeographyInfo"] | null;
            /** Next Cursor */
            next_cursor: string | null;
            provenance: components["schemas"]["Provenance"];
            qc_policy?: components["schemas"]["QcPolicy"] | null;
            result: components["schemas"]["ResultTable"];
            time_range?: components["schemas"]["TimeInterval"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Column */
        Column: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Unit */
            unit?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CoverageResponse */
        CoverageResponse: {
            coverage: components["schemas"]["CoverageSummary"];
            environment: components["schemas"]["Environment"];
            geography: components["schemas"]["GeographyInfo"];
            /** Slots */
            slots: components["schemas"]["SlotCoverage"][];
        } & {
            [key: string]: unknown;
        };
        /** CoverageSummary */
        CoverageSummary: {
            /** Estimated Levels */
            estimated_levels: number;
            /** Estimated Profiles */
            estimated_profiles: number;
            /** Missing */
            missing: components["schemas"]["SlotCoverage"][];
            /** Months */
            months: string[];
            /** Partial */
            partial: boolean;
            requested: components["schemas"]["TimeInterval"];
            /** Slots Covered */
            slots_covered: number;
            /** Slots Empty Verified */
            slots_empty_verified: number;
            /** Slots Missing */
            slots_missing: number;
            /** Slots Total */
            slots_total: number;
            /** Tiles */
            tiles: components["schemas"]["Tile"][];
        } & {
            [key: string]: unknown;
        };
        /** Environment */
        Environment: {
            /** Completed Runs */
            completed_runs: number;
            hot_tier?: components["schemas"]["TimeInterval"] | null;
            /** Id */
            id: string;
            /** Ingested At */
            ingested_at?: string | null;
            /** Latest Run */
            latest_run?: string | null;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            postgresql_window?: components["schemas"]["TimeInterval"] | null;
            /** Reference Time */
            reference_time?: string | null;
            source_retrieved?: components["schemas"]["TimeInterval"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Details */
            details: {
                [key: string]: string;
            }[];
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Execution */
        Execution: {
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Estimated Levels */
            estimated_levels?: number | null;
            /** Estimated Profiles */
            estimated_profiles?: number | null;
            /** Partitions */
            partitions?: {
                [key: string]: unknown;
            }[] | null;
            /** Rows */
            rows?: number | null;
            /** Run Ids */
            run_ids?: string[] | null;
            /** Source */
            source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** FloatResponse */
        FloatResponse: {
            environment: components["schemas"]["Environment"];
            float: components["schemas"]["FloatSummary"];
            /** Next Cursor */
            next_cursor: string | null;
            provenance: components["schemas"]["Provenance"];
            time_range?: components["schemas"]["TimeInterval"] | null;
            trajectory: components["schemas"]["ResultTable"];
        } & {
            [key: string]: unknown;
        };
        /** FloatSummary */
        FloatSummary: {
            /** First Cycle */
            first_cycle?: number | null;
            /** First Observed At */
            first_observed_at?: string | null;
            /** Last Cycle */
            last_cycle?: number | null;
            /** Last Latitude */
            last_latitude?: number | null;
            /** Last Longitude */
            last_longitude?: number | null;
            /** Last Observed At */
            last_observed_at?: string | null;
            /** Platform Number */
            platform_number: string;
            /** Profile Count */
            profile_count: number;
            /** Source */
            source: string;
        } & {
            [key: string]: unknown;
        };
        /** GeographyInfo */
        GeographyInfo: {
            /** Boxes */
            boxes?: components["schemas"]["Box"][] | null;
            /** Clipped */
            clipped?: boolean | null;
            /** Kind */
            kind: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Name */
            name?: string | null;
            /** Radius M */
            radius_m?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /** Version */
            version?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ProfileHeader */
        ProfileHeader: {
            /** Content Hash */
            content_hash: string;
            /** Cycle Number */
            cycle_number: number;
            /** Direction */
            direction: string;
            /** Id */
            id: string;
            /** Last Scientific Run Id */
            last_scientific_run_id: string;
            /** Latitude */
            latitude: number;
            /** Level Count */
            level_count: number;
            /** Longitude */
            longitude: number;
            /** Observation Month */
            observation_month: string;
            /** Observed At */
            observed_at: string;
            /** Platform Number */
            platform_number: string;
            /** Source */
            source: string;
            /** Source Profile Id */
            source_profile_id: string;
        } & {
            [key: string]: unknown;
        };
        /** ProfileResponse */
        ProfileResponse: {
            environment: components["schemas"]["Environment"];
            levels: components["schemas"]["ResultTable"];
            profile: components["schemas"]["ProfileHeader"];
            provenance: components["schemas"]["Provenance"];
            qc_policy: components["schemas"]["QcPolicy"];
        } & {
            [key: string]: unknown;
        };
        /** Provenance */
        Provenance: {
            /** Application Commit */
            application_commit: string;
            /** Attribution */
            attribution: {
                [key: string]: string;
            };
            coverage?: components["schemas"]["CoverageSummary"] | null;
            environment: components["schemas"]["Environment"];
            execution: components["schemas"]["Execution"];
            geography?: components["schemas"]["GeographyInfo"] | null;
            /** Plan Sha256 */
            plan_sha256?: string | null;
            /** Result Sha256 */
            result_sha256: string;
            /** Source */
            source: string;
            /** Transformation */
            transformation: string;
            /** Versions */
            versions: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** QcPolicy */
        QcPolicy: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * QueryRequest
         * @description The ``stage2-plan-v1`` document (documentation shape only).
         *
         *     Every field is validated by the query engine, which answers ``plan_invalid`` with one
         *     registered detail per violation; this model therefore never rejects a body itself.
         */
        QueryRequest: {
            /**
             * Dataset
             * @default core
             */
            dataset: string | null;
            /**
             * Depth Dbar
             * @default null
             */
            depth_dbar: {
                [key: string]: unknown;
            } | null;
            /**
             * Geography
             * @default null
             */
            geography: {
                [key: string]: unknown;
            } | null;
            /**
             * Operation
             * @default null
             */
            operation: {
                [key: string]: unknown;
            } | null;
            /**
             * Presentation
             * @default null
             */
            presentation: {
                [key: string]: unknown;
            } | null;
            /**
             * Qc Policy
             * @default science_ready
             */
            qc_policy: string | null;
            /**
             * Time Range
             * @default null
             */
            time_range: {
                [key: string]: unknown;
            } | null;
            /**
             * Variables
             * @default null
             */
            variables: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /** QueryResponse */
        QueryResponse: {
            chart: components["schemas"]["ChartSpec"] | null;
            coverage: components["schemas"]["CoverageSummary"];
            execution: components["schemas"]["Execution"];
            /** Interpretation */
            interpretation: {
                [key: string]: unknown;
            };
            /** Missing */
            missing: components["schemas"]["SlotCoverage"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Partial */
            partial: boolean;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            provenance: components["schemas"]["Provenance"];
            result: components["schemas"]["ResultTable"];
        } & {
            [key: string]: unknown;
        };
        /** ResultTable */
        ResultTable: {
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Missing Value Policy */
            missing_value_policy: string;
            /** Non Finite Values */
            non_finite_values: number;
            /** Row Count */
            row_count: number;
            /** Rows */
            rows: unknown[][];
        } & {
            [key: string]: unknown;
        };
        /** SlotCoverage */
        SlotCoverage: {
            /** Gaps */
            gaps: string[];
            /** Levels */
            levels: number;
            /** Month */
            month: string;
            /** Parts */
            parts: number;
            /** Profiles */
            profiles: number;
            /** Slot */
            slot: string;
            /** State */
            state: string;
            tile: components["schemas"]["Tile"];
        } & {
            [key: string]: unknown;
        };
        /** Tile */
        Tile: {
            /** South */
            south: number;
            /** West */
            west: number;
        } & {
            [key: string]: unknown;
        };
        /** TimeInterval */
        TimeInterval: {
            /** End */
            end?: string | null;
            /** Start */
            start?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_coverage_v1_catalog_coverage_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                region?: string | null;
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    catalog_parameters_v1_catalog_parameters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    floats_v1_floats_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                region?: string | null;
                bbox?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    float_detail_v1_floats__platform_number__get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                platform_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloatResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    profiles_v1_profiles_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                region?: string | null;
                bbox?: string | null;
                platform_number?: string | null;
                depth_min?: number | null;
                depth_max?: number | null;
                qc_policy?: string;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_v1_profiles__profile_id__get: {
        parameters: {
            query?: {
                qc_policy?: string;
                depth_min?: number | null;
                depth_max?: number | null;
            };
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
